// Curated showcase events — a reliable, hand-picked baseline of genuinely
// appealing UK/Scotland local things. Always included so the map stays alive
// even when live feeds (Ticketmaster / OpenActive / RSS) are thin or empty.
// Live ingested events layer on top of these.

function addDays(days) {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

// deterministic jitter so co-located events don't stack on one pixel
function near(base, seed) {
  const j = ((seed * 9301 + 49297) % 233280) / 233280;
  return base + (j - 0.5) * 0.04;
}

const RAW = [
  { city: "Edinburgh", lat: 55.9533, lng: -3.1883, day: 0, time: "10:00",
    name: "Stockbridge Sunday Market", venue: "Saunders Street, Stockbridge",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Street food, local makers and bakers along the Water of Leith.",
    url: "https://www.stockbridgemarket.com", likes: 34, trust: "community" },
  { city: "Edinburgh", lat: 55.9486, lng: -3.1999, day: 1, time: "19:30",
    name: "Folk Night at Sandy Bell's", venue: "Sandy Bell's, Forrest Road",
    category: ["music"], cost: "free", vibe: "lively", indoor: "indoor",
    summary: "Long-running traditional Scottish music session. Turn up and listen.",
    url: "https://www.sandybellsedinburgh.co.uk", likes: 21, trust: "community" },
  { city: "Edinburgh", lat: 55.9579, lng: -3.1737, day: 3, time: "18:00",
    name: "Museum Lates: After Hours", venue: "National Museum of Scotland",
    category: ["family", "wellbeing"], cost: "paid", vibe: "social", indoor: "indoor",
    summary: "Galleries open late with talks, a bar and live sets.",
    url: "https://www.nms.ac.uk/national-museum-of-scotland", likes: 48, trust: "official" },
  { city: "Edinburgh", lat: 55.9441, lng: -3.1618, day: 6, time: "09:30",
    name: "Holyrood Park Parkrun & Picnic", venue: "Holyrood Park",
    category: ["sports", "outdoors"], cost: "free", vibe: "energetic", indoor: "outdoor",
    activity_level: "high",
    summary: "Free timed 5k followed by a community picnic under Arthur's Seat.",
    url: "https://www.parkrun.org.uk", likes: 17, trust: "community" },

  { city: "Glasgow", lat: 55.8642, lng: -4.2518, day: 0, time: "12:00",
    name: "Barras Market Weekender", venue: "The Barras, Gallowgate",
    category: ["market", "family"], cost: "free", vibe: "lively", indoor: "mixed",
    summary: "Glasgow's iconic weekend market — vinyl, vintage and street food.",
    url: "https://www.glasgowbarrowland.com", likes: 41, trust: "official" },
  { city: "Glasgow", lat: 55.8723, lng: -4.2901, day: 2, time: "20:00",
    name: "King Tut's New Band Night", venue: "King Tut's Wah Wah Hut",
    category: ["music"], cost: "paid", vibe: "lively", indoor: "indoor",
    summary: "Four up-and-coming bands in the room that discovered Oasis.",
    url: "https://www.kingtuts.co.uk", likes: 29, trust: "community" },
  { city: "Glasgow", lat: 55.8685, lng: -4.2912, day: 4, time: "11:00",
    name: "Kelvingrove Free Family Day", venue: "Kelvingrove Art Gallery",
    category: ["family", "charity"], cost: "free", vibe: "relaxed", indoor: "indoor",
    summary: "Hands-on art trails and the daily organ recital. Buggy friendly.",
    url: "https://www.glasgowlife.org.uk/museums/venues/kelvingrove-art-gallery-and-museum", likes: 38, trust: "official" },
  { city: "Glasgow", lat: 55.8554, lng: -4.2649, day: 8, time: "10:00",
    name: "Southside Makers' Market", venue: "Queen's Park Arena",
    category: ["market", "outdoors"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Independent makers, plants and coffee in the park.",
    url: "https://www.queensparkglasgow.org", likes: 19, trust: "community" },

  { city: "Dundee", lat: 56.4575, lng: -2.9707, day: 1, time: "10:00",
    name: "V&A Dundee: Design Workshop", venue: "V&A Dundee",
    category: ["family", "wellbeing"], cost: "donation", vibe: "creative", indoor: "indoor",
    summary: "Drop-in making session for all ages on the waterfront.",
    url: "https://www.vam.ac.uk/dundee", likes: 26, trust: "official" },
  { city: "Dundee", lat: 56.4640, lng: -2.9800, day: 5, time: "13:00",
    name: "Riverside Food & Craft Fair", venue: "Slessor Gardens",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Local traders, live music and a kids' corner by the Tay.",
    url: "https://www.dundee.com", likes: 15, trust: "official" },

  { city: "Aberdeen", lat: 57.1497, lng: -2.0943, day: 2, time: "11:00",
    name: "Aberdeen Country Fair", venue: "Belmont Street",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Monthly farmers' and artisan market in the heart of the city.",
    url: "https://www.aberdeencity.gov.uk", likes: 22, trust: "official" },
  { city: "Aberdeen", lat: 57.1430, lng: -2.0980, day: 7, time: "19:00",
    name: "Lemon Tree Live: Local Showcase", venue: "The Lemon Tree",
    category: ["music"], cost: "paid", vibe: "lively", indoor: "indoor",
    summary: "North-east songwriters share a bill at this beloved venue.",
    url: "https://www.aberdeenperformingarts.com", likes: 18, trust: "community" },

  { city: "Stirling", lat: 56.1165, lng: -3.9369, day: 3, time: "10:30",
    name: "Castle Hill Heritage Walk", venue: "Stirling Castle Esplanade",
    category: ["outdoors", "wellbeing"], cost: "donation", vibe: "relaxed", indoor: "outdoor",
    activity_level: "medium",
    summary: "Guided walk through the old town with big views and bigger stories.",
    url: "https://www.yourstirling.com", likes: 12, trust: "community" },
  { city: "Perth", lat: 56.3950, lng: -3.4308, day: 4, time: "18:30",
    name: "Perth Riverside Ceilidh", venue: "Perth Concert Hall",
    category: ["music", "family"], cost: "paid", vibe: "lively", indoor: "indoor",
    summary: "All-welcome ceilidh with a live band and a caller — no skill needed.",
    url: "https://www.horsecross.co.uk", likes: 31, trust: "official" },
  { city: "Inverness", lat: 57.4778, lng: -4.2247, day: 6, time: "11:00",
    name: "Highland Makers' Market", venue: "Eden Court",
    category: ["market", "charity"], cost: "free", vibe: "relaxed", indoor: "mixed",
    summary: "Highland crafts, food and a charity tombola by the river Ness.",
    url: "https://eden-court.co.uk", likes: 14, trust: "official" },
  { city: "St Andrews", lat: 56.3398, lng: -2.7967, day: 9, time: "09:00",
    name: "West Sands Beach Clean", venue: "West Sands Beach",
    category: ["charity", "outdoors"], cost: "free", vibe: "purposeful", indoor: "outdoor",
    activity_level: "medium",
    summary: "Community beach clean — gloves and bags provided, dogs welcome.",
    url: "https://www.standrews.com", likes: 9, trust: "community" },

  { city: "Manchester", lat: 53.4808, lng: -2.2426, day: 1, time: "11:00",
    name: "Northern Quarter Makers' Market", venue: "Stevenson Square",
    category: ["market", "family"], cost: "free", vibe: "lively", indoor: "outdoor",
    summary: "Independent design, records and street food in the NQ.",
    url: "https://www.visitmanchester.com", likes: 36, trust: "official" },
  { city: "Manchester", lat: 53.4751, lng: -2.2300, day: 5, time: "20:00",
    name: "Band on the Wall: New Talent", venue: "Band on the Wall",
    category: ["music"], cost: "paid", vibe: "lively", indoor: "indoor",
    summary: "Genre-spanning night of emerging Manchester acts.",
    url: "https://bandonthewall.org", likes: 27, trust: "community" },
  { city: "Leeds", lat: 53.8008, lng: -1.5491, day: 2, time: "10:00",
    name: "Kirkgate Vintage & Flea", venue: "Kirkgate Market",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "indoor",
    summary: "Vintage clothing, vinyl and bric-a-brac in a Victorian market hall.",
    url: "https://www.leeds.gov.uk/leedsmarkets", likes: 20, trust: "official" },
  { city: "Newcastle", lat: 54.9783, lng: -1.6178, day: 3, time: "12:00",
    name: "Quayside Sunday Market", venue: "Newcastle Quayside",
    category: ["market", "outdoors"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Riverside stalls under the Tyne Bridge — food, art and plants.",
    url: "https://newcastlegateshead.com", likes: 24, trust: "official" },
  { city: "Liverpool", lat: 53.4084, lng: -2.9916, day: 4, time: "18:00",
    name: "Baltic Triangle Street Food", venue: "Baltic Market",
    category: ["market", "family"], cost: "free", vibe: "lively", indoor: "indoor",
    summary: "Indie kitchens and local brewers in the city's creative quarter.",
    url: "https://balticmarket.co.uk", likes: 33, trust: "community" },
  { city: "Bristol", lat: 51.4545, lng: -2.5879, day: 2, time: "10:00",
    name: "Tobacco Factory Sunday Market", venue: "Tobacco Factory, Southville",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "mixed",
    summary: "Farmers, makers and brunch in a Bristol institution.",
    url: "https://tobaccofactory.com", likes: 28, trust: "official" },
  { city: "Bristol", lat: 51.4490, lng: -2.6000, day: 7, time: "10:30",
    name: "Ashton Court Community Walk", venue: "Ashton Court Estate",
    category: ["outdoors", "wellbeing"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    activity_level: "medium",
    summary: "Friendly group walk through 850 acres of deer park and woodland.",
    url: "https://www.bristol.gov.uk", likes: 11, trust: "community" },
  { city: "Cardiff", lat: 51.4816, lng: -3.1791, day: 5, time: "11:00",
    name: "Riverside Real Food Market", venue: "Fitzhamon Embankment",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Wales' longest-running farmers' market on the Taff.",
    url: "https://riversidemarket.org.uk", likes: 16, trust: "official" },
  { city: "York", lat: 53.9600, lng: -1.0873, day: 6, time: "10:00",
    name: "Shambles Makers' Fair", venue: "Parliament Street",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Yorkshire makers and producers in the old city centre.",
    url: "https://www.visityork.org", likes: 13, trust: "official" },
  { city: "Brighton", lat: 50.8225, lng: -0.1372, day: 1, time: "11:00",
    name: "Open Market Makers' Sunday", venue: "Brighton Open Market",
    category: ["market", "family"], cost: "free", vibe: "lively", indoor: "mixed",
    summary: "Independent traders, street food and live buskers.",
    url: "https://brightonopenmarket.co.uk", likes: 25, trust: "official" },
  { city: "Brighton", lat: 50.8290, lng: -0.1500, day: 8, time: "07:30",
    name: "Seafront Sunrise Yoga", venue: "Brighton Beach, Hove Lawns",
    category: ["wellbeing", "outdoors"], cost: "donation", vibe: "calm", indoor: "outdoor",
    activity_level: "low",
    summary: "Donation-based beach yoga as the sun comes up. Bring a mat.",
    url: "https://www.visitbrighton.com", likes: 22, trust: "community" },
  { city: "London", lat: 51.5074, lng: -0.1278, day: 0, time: "11:00",
    name: "Columbia Road Flower Market", venue: "Columbia Road, Bethnal Green",
    category: ["market", "family"], cost: "free", vibe: "lively", indoor: "outdoor",
    summary: "The famous Sunday flower market — go early, leave with a fern.",
    url: "https://columbiaroad.info", likes: 52, trust: "official" },
  { city: "London", lat: 51.5045, lng: -0.0865, day: 3, time: "10:00",
    name: "Borough Market Producers' Day", venue: "Borough Market, Southwark",
    category: ["market", "family"], cost: "free", vibe: "lively", indoor: "mixed",
    summary: "Tastings and demos from the market's independent producers.",
    url: "https://boroughmarket.org.uk", likes: 44, trust: "official" },
  { city: "London", lat: 51.5390, lng: -0.1426, day: 5, time: "14:00",
    name: "Camden Community Garden Day", venue: "Camden Garden Centre",
    category: ["charity", "outdoors", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Volunteer planting, plant swap and a cake stall for charity.",
    url: "https://www.camden.gov.uk", likes: 10, trust: "community" },
];

const W3W = ["spice.ramp.state", "stows.ages.take", "cafe.robot.daring", "led.gone.needs",
  "trip.tides.salt", "rock.faced.bands", "soft.melt.dined", "vase.curve.lined"];

export function getShowcaseEvents() {
  return RAW.map((e, i) => {
    const start = addDays(e.day);
    const verification = e.trust === "community" ? "community-submitted" : "feed-listing";
    return {
      id: `showcase_${i}_${e.city.toLowerCase().replace(/\s+/g, "")}`,
      name: e.name,
      start_date: start,
      end_date: start,
      time: e.time,
      category: e.category,
      cost: e.cost,
      venue: e.venue,
      city: e.city,
      url: e.url,
      source_event_url: e.url,
      source_feed_url: "",
      what3words: W3W[i % W3W.length],
      lat: near(e.lat, i + 1),
      lng: near(e.lng, i + 7),
      summary: e.summary,
      vibe: e.vibe,
      indoor: e.indoor,
      activity_level: e.activity_level || "low",
      audience: ["all-ages"],
      accessibility: ["step-free"],
      source: "showcase",
      source_trust: e.trust === "community" ? "community" : "official",
      verification_status: verification,
      popularity: e.likes,
      last_seen_at: new Date().toISOString(),
    };
  });
}

export default getShowcaseEvents;
