// Single source of truth for the curated showcase dataset.
//
// Imported by BOTH the server (server/adapters/sources/showcaseEvents.js) and
// the frontend offline fallback (src/lib/sampleEvents.js). Edit events here once.
//
// These are hand-picked, realistic local "days out" — markets, gigs, festivals,
// family days, museum lates, ceilidhs, makers' fairs — weighted Scotland-first
// but UK-wide. Dates are built relative to "today" so the map always looks
// current. Events are spread across the next ~3 weeks with several per day so
// the map and date strip feel full.

function addDaysYmd(days) {
  const d = new Date();
  d.setHours(0, 0, 0, 0);
  d.setDate(d.getDate() + days);
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

// deterministic jitter so co-located events don't stack on one pixel
function near(base, seed) {
  const j = ((seed * 9301 + 49297) % 233280) / 233280;
  return base + (j - 0.5) * 0.04;
}

const WINDOW_DAYS = 21; // how far ahead recurring/evergreen entries reach

// days from today until the next given weekday (0=Sun … 6=Sat); 0 if today
function nextDow(dow) {
  const today = new Date().getDay();
  return (dow - today + 7) % 7;
}

const RAW = [
  // ---- Edinburgh ----
  { city: "Edinburgh", lat: 55.9533, lng: -3.1883, repeat: "weekly", dow: 0, time: "10:00",
    name: "Stockbridge Sunday Market", venue: "Saunders Street, Stockbridge",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Street food, local makers and bakers along the Water of Leith.",
    url: "https://www.stockbridgemarket.com", likes: 34, trust: "community" },
  { city: "Edinburgh", lat: 55.9486, lng: -3.1999, day: 1, time: "19:30",
    name: "Folk Night at Sandy Bell's", venue: "Sandy Bell's, Forrest Road",
    category: ["music"], cost: "free", vibe: "lively", indoor: "indoor",
    summary: "Long-running traditional Scottish music session. Turn up and listen.",
    url: "https://www.sandybellsedinburgh.co.uk", likes: 21, trust: "community" },
  { city: "Edinburgh", lat: 55.9579, lng: -3.1737, day: 3, time: "18:00",
    name: "Museum Lates: After Hours", venue: "National Museum of Scotland",
    category: ["family", "wellbeing"], cost: "paid", vibe: "social", indoor: "indoor",
    summary: "Galleries open late with talks, a bar and live sets.",
    url: "https://www.nms.ac.uk/national-museum-of-scotland", likes: 48, trust: "official" },
  { city: "Edinburgh", lat: 55.9441, lng: -3.1618, day: 6, time: "09:30",
    name: "Holyrood Park Parkrun & Picnic", venue: "Holyrood Park",
    category: ["sports", "outdoors"], cost: "free", vibe: "energetic", indoor: "outdoor",
    activity_level: "high",
    summary: "Free timed 5k followed by a community picnic under Arthur's Seat.",
    url: "https://www.parkrun.org.uk", likes: 17, trust: "community" },
  { city: "Edinburgh", lat: 55.9521, lng: -3.1965, day: 10, time: "11:00",
    name: "Grassmarket Vintage Fair", venue: "Grassmarket",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Vintage clothing, vinyl and crafts under the castle.",
    url: "https://www.greatergrassmarket.co.uk", likes: 23, trust: "community" },

  // ---- Glasgow ----
  { city: "Glasgow", lat: 55.8642, lng: -4.2518, repeat: "weekly", dow: 6, time: "12:00",
    name: "Barras Market Weekender", venue: "The Barras, Gallowgate",
    category: ["market", "family"], cost: "free", vibe: "lively", indoor: "mixed",
    summary: "Glasgow's iconic weekend market — vinyl, vintage and street food.",
    url: "https://www.glasgowbarrowland.com", likes: 41, trust: "official" },
  { city: "Glasgow", lat: 55.8723, lng: -4.2901, day: 2, time: "20:00",
    name: "King Tut's New Band Night", venue: "King Tut's Wah Wah Hut",
    category: ["music"], cost: "paid", vibe: "lively", indoor: "indoor",
    summary: "Four up-and-coming bands in the room that discovered Oasis.",
    url: "https://www.kingtuts.co.uk", likes: 29, trust: "community" },
  { city: "Glasgow", lat: 55.8685, lng: -4.2912, day: 4, time: "11:00",
    name: "Kelvingrove Free Family Day", venue: "Kelvingrove Art Gallery",
    category: ["family", "charity"], cost: "free", vibe: "relaxed", indoor: "indoor",
    summary: "Hands-on art trails and the daily organ recital. Buggy friendly.",
    url: "https://www.glasgowlife.org.uk/museums/venues/kelvingrove-art-gallery-and-museum", likes: 38, trust: "official" },
  { city: "Glasgow", lat: 55.8554, lng: -4.2649, day: 8, time: "10:00",
    name: "Southside Makers' Market", venue: "Queen's Park Arena",
    category: ["market", "outdoors"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Independent makers, plants and coffee in the park.",
    url: "https://www.queensparkglasgow.org", likes: 19, trust: "community" },
  { city: "Glasgow", lat: 55.8700, lng: -4.2700, day: 0, time: "14:00",
    name: "Botanic Gardens Nature Walk", venue: "Glasgow Botanic Gardens",
    category: ["outdoors", "wellbeing"], cost: "free", vibe: "calm", indoor: "outdoor",
    activity_level: "low",
    summary: "Gentle guided walk through the glasshouses and the Kibble Palace.",
    url: "https://www.glasgowbotanicgardens.com", likes: 16, trust: "community" },
  { city: "Glasgow", lat: 55.8580, lng: -4.2590, day: 12, time: "17:00",
    name: "Govanhill Community Food Fair", venue: "Govanhill Baths",
    category: ["market", "charity", "family"], cost: "donation", vibe: "social", indoor: "mixed",
    summary: "Community kitchens, world food and a swap shop in the old baths.",
    url: "https://www.govanhillbaths.com", likes: 13, trust: "community" },

  // ---- Dundee ----
  { city: "Dundee", lat: 56.4575, lng: -2.9707, day: 1, time: "10:00",
    name: "V&A Dundee: Design Workshop", venue: "V&A Dundee",
    category: ["family", "wellbeing"], cost: "donation", vibe: "creative", indoor: "indoor",
    summary: "Drop-in making session for all ages on the waterfront.",
    url: "https://www.vam.ac.uk/dundee", likes: 26, trust: "official" },
  { city: "Dundee", lat: 56.4640, lng: -2.9800, day: 5, time: "13:00",
    name: "Riverside Food & Craft Fair", venue: "Slessor Gardens",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Local traders, live music and a kids' corner by the Tay.",
    url: "https://www.dundee.com", likes: 15, trust: "official" },
  { city: "Dundee", lat: 56.4620, lng: -2.9620, day: 11, time: "19:00",
    name: "Beer & Music at Bellrock", venue: "Bellrock Square, Waterfront",
    category: ["music", "market"], cost: "free", vibe: "lively", indoor: "outdoor",
    summary: "Local breweries and live acoustic sets by the waterfront.",
    url: "https://www.dundee.com", likes: 18, trust: "community" },

  // ---- Aberdeen ----
  { city: "Aberdeen", lat: 57.1497, lng: -2.0943, day: 2, time: "11:00",
    name: "Aberdeen Country Fair", venue: "Belmont Street",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Monthly farmers' and artisan market in the heart of the city.",
    url: "https://www.aberdeencity.gov.uk", likes: 22, trust: "official" },
  { city: "Aberdeen", lat: 57.1430, lng: -2.0980, day: 7, time: "19:00",
    name: "Lemon Tree Live: Local Showcase", venue: "The Lemon Tree",
    category: ["music"], cost: "paid", vibe: "lively", indoor: "indoor",
    summary: "North-east songwriters share a bill at this beloved venue.",
    url: "https://www.aberdeenperformingarts.com", likes: 18, trust: "community" },
  { city: "Aberdeen", lat: 57.1390, lng: -2.0900, day: 13, time: "10:00",
    name: "Duthie Park Plant Swap", venue: "Duthie Park Winter Gardens",
    category: ["outdoors", "charity"], cost: "free", vibe: "relaxed", indoor: "mixed",
    summary: "Bring a cutting, take a cutting — plus tea and cake for charity.",
    url: "https://www.aberdeencity.gov.uk", likes: 10, trust: "community" },

  // ---- Smaller Scottish towns ----
  { city: "Stirling", lat: 56.1165, lng: -3.9369, day: 3, time: "10:30",
    name: "Castle Hill Heritage Walk", venue: "Stirling Castle Esplanade",
    category: ["outdoors", "wellbeing"], cost: "donation", vibe: "relaxed", indoor: "outdoor",
    activity_level: "medium",
    summary: "Guided walk through the old town with big views and bigger stories.",
    url: "https://www.yourstirling.com", likes: 12, trust: "community" },
  { city: "Perth", lat: 56.3950, lng: -3.4308, day: 4, time: "18:30",
    name: "Perth Riverside Ceilidh", venue: "Perth Concert Hall",
    category: ["music", "family"], cost: "paid", vibe: "lively", indoor: "indoor",
    summary: "All-welcome ceilidh with a live band and a caller — no skill needed.",
    url: "https://www.horsecross.co.uk", likes: 31, trust: "official" },
  { city: "Inverness", lat: 57.4778, lng: -4.2247, day: 6, time: "11:00",
    name: "Highland Makers' Market", venue: "Eden Court",
    category: ["market", "charity"], cost: "free", vibe: "relaxed", indoor: "mixed",
    summary: "Highland crafts, food and a charity tombola by the river Ness.",
    url: "https://eden-court.co.uk", likes: 14, trust: "official" },
  { city: "St Andrews", lat: 56.3398, lng: -2.7967, day: 9, time: "09:00",
    name: "West Sands Beach Clean", venue: "West Sands Beach",
    category: ["charity", "outdoors"], cost: "free", vibe: "purposeful", indoor: "outdoor",
    activity_level: "medium",
    summary: "Community beach clean — gloves and bags provided, dogs welcome.",
    url: "https://www.standrews.com", likes: 9, trust: "community" },
  { city: "Falkirk", lat: 56.0194, lng: -3.7556, day: 1, time: "10:00",
    name: "Kelpies Family Fun Day", venue: "The Helix Park",
    category: ["family", "outdoors"], cost: "free", vibe: "lively", indoor: "outdoor",
    summary: "Activities, food trucks and trails beneath the giant Kelpies.",
    url: "https://www.thehelix.co.uk", likes: 27, trust: "official" },
  { city: "Dunfermline", lat: 56.0719, lng: -3.4520, day: 5, time: "11:00",
    name: "Pittencrieff Park Makers' Fair", venue: "Pittencrieff Park",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Crafts, plants and street food in Dunfermline's beloved Glen.",
    url: "https://www.onfife.com", likes: 11, trust: "community" },
  { city: "Ayr", lat: 55.4586, lng: -4.6292, day: 7, time: "10:00",
    name: "Ayr Beachfront Market", venue: "Ayr Esplanade",
    category: ["market", "outdoors", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Seaside stalls, ice cream and live buskers along the prom.",
    url: "https://www.ayrshire.scot", likes: 13, trust: "community" },
  { city: "Paisley", lat: 55.8470, lng: -4.4237, day: 8, time: "18:00",
    name: "Paisley Abbey Heritage Late", venue: "Paisley Abbey",
    category: ["family", "wellbeing"], cost: "donation", vibe: "calm", indoor: "indoor",
    summary: "Evening tours of the abbey with choir rehearsal and candlelight.",
    url: "https://www.paisley.org.uk", likes: 12, trust: "official" },
  { city: "Oban", lat: 56.4151, lng: -5.4717, day: 10, time: "12:00",
    name: "Oban Seafood & Harbour Day", venue: "Oban Harbour",
    category: ["market", "food", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Fresh-off-the-boat seafood stalls and a small craft market.",
    url: "https://www.oban.org.uk", likes: 20, trust: "community" },
  { city: "Pitlochry", lat: 56.7039, lng: -3.7300, day: 14, time: "10:30",
    name: "Highland Perthshire Nature Walk", venue: "Pitlochry Dam",
    category: ["outdoors", "wellbeing"], cost: "free", vibe: "calm", indoor: "outdoor",
    activity_level: "medium",
    summary: "Riverside ranger walk past the salmon ladder and woodland.",
    url: "https://www.pitlochry.org", likes: 9, trust: "community" },
  { city: "Dumfries", lat: 55.0700, lng: -3.6030, day: 9, time: "11:00",
    name: "Dumfries Riverside Farmers' Market", venue: "Whitesands",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Galloway producers and bakers along the river Nith.",
    url: "https://www.dgwgo.com", likes: 8, trust: "community" },
  { city: "Kirkcaldy", lat: 56.1132, lng: -3.1610, day: 12, time: "10:00",
    name: "Kirkcaldy Esplanade Vintage Fair", venue: "Kirkcaldy Esplanade",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Vintage, retro and handmade stalls by the Fife coast.",
    url: "https://www.onfife.com", likes: 10, trust: "community" },

  // ---- England ----
  { city: "Manchester", lat: 53.4808, lng: -2.2426, day: 1, time: "11:00",
    name: "Northern Quarter Makers' Market", venue: "Stevenson Square",
    category: ["market", "family"], cost: "free", vibe: "lively", indoor: "outdoor",
    summary: "Independent design, records and street food in the NQ.",
    url: "https://www.visitmanchester.com", likes: 36, trust: "official" },
  { city: "Manchester", lat: 53.4751, lng: -2.2300, day: 5, time: "20:00",
    name: "Band on the Wall: New Talent", venue: "Band on the Wall",
    category: ["music"], cost: "paid", vibe: "lively", indoor: "indoor",
    summary: "Genre-spanning night of emerging Manchester acts.",
    url: "https://bandonthewall.org", likes: 27, trust: "community" },
  { city: "Leeds", lat: 53.8008, lng: -1.5491, day: 2, time: "10:00",
    name: "Kirkgate Vintage & Flea", venue: "Kirkgate Market",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "indoor",
    summary: "Vintage clothing, vinyl and bric-a-brac in a Victorian market hall.",
    url: "https://www.leeds.gov.uk/leedsmarkets", likes: 20, trust: "official" },
  { city: "Newcastle", lat: 54.9783, lng: -1.6178, day: 3, time: "12:00",
    name: "Quayside Sunday Market", venue: "Newcastle Quayside",
    category: ["market", "outdoors"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Riverside stalls under the Tyne Bridge — food, art and plants.",
    url: "https://newcastlegateshead.com", likes: 24, trust: "official" },
  { city: "Liverpool", lat: 53.4084, lng: -2.9916, day: 4, time: "18:00",
    name: "Baltic Triangle Street Food", venue: "Baltic Market",
    category: ["market", "family"], cost: "free", vibe: "lively", indoor: "indoor",
    summary: "Indie kitchens and local brewers in the city's creative quarter.",
    url: "https://balticmarket.co.uk", likes: 33, trust: "community" },
  { city: "Sheffield", lat: 53.3811, lng: -1.4701, day: 6, time: "11:00",
    name: "Peace Gardens Makers' Market", venue: "Peace Gardens",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Steel-city makers, food and live music in the city centre.",
    url: "https://www.welcometosheffield.co.uk", likes: 15, trust: "community" },
  { city: "Nottingham", lat: 52.9548, lng: -1.1581, day: 8, time: "10:00",
    name: "Sneinton Avenues Vintage Market", venue: "Sneinton Market",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "mixed",
    summary: "Creative quarter market — makers, coffee and street food.",
    url: "https://sneintonmarket.com", likes: 14, trust: "community" },
  { city: "Bristol", lat: 51.4545, lng: -2.5879, day: 2, time: "10:00",
    name: "Tobacco Factory Sunday Market", venue: "Tobacco Factory, Southville",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "mixed",
    summary: "Farmers, makers and brunch in a Bristol institution.",
    url: "https://tobaccofactory.com", likes: 28, trust: "official" },
  { city: "Bristol", lat: 51.4490, lng: -2.6000, day: 7, time: "10:30",
    name: "Ashton Court Community Walk", venue: "Ashton Court Estate",
    category: ["outdoors", "wellbeing"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    activity_level: "medium",
    summary: "Friendly group walk through 850 acres of deer park and woodland.",
    url: "https://www.bristol.gov.uk", likes: 11, trust: "community" },
  { city: "Bath", lat: 51.3811, lng: -2.3590, day: 11, time: "10:00",
    name: "Green Park Station Makers' Market", venue: "Green Park Station",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "indoor",
    summary: "Artisan food and crafts under a restored Victorian train shed.",
    url: "https://www.greenparkstation.co.uk", likes: 17, trust: "community" },
  { city: "Cardiff", lat: 51.4816, lng: -3.1791, day: 5, time: "11:00",
    name: "Riverside Real Food Market", venue: "Fitzhamon Embankment",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Wales' longest-running farmers' market on the Taff.",
    url: "https://riversidemarket.org.uk", likes: 16, trust: "official" },
  { city: "York", lat: 53.9600, lng: -1.0873, day: 6, time: "10:00",
    name: "Shambles Makers' Fair", venue: "Parliament Street",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Yorkshire makers and producers in the old city centre.",
    url: "https://www.visityork.org", likes: 13, trust: "official" },
  { city: "Norwich", lat: 52.6309, lng: 1.2974, day: 9, time: "10:00",
    name: "Norwich Lanes Vintage Fair", venue: "The Norwich Lanes",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "mixed",
    summary: "Independent shops, makers and street food across the Lanes.",
    url: "https://www.norwichlanes.co.uk", likes: 12, trust: "community" },
  { city: "Cambridge", lat: 52.2053, lng: 0.1218, day: 4, time: "10:00",
    name: "Cambridge Market Square Fair", venue: "Market Square",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Daily market with a weekend makers' and food line-up.",
    url: "https://www.cambridge.gov.uk", likes: 18, trust: "official" },
  { city: "Oxford", lat: 51.7520, lng: -1.2577, day: 10, time: "10:00",
    name: "Gloucester Green Makers' Market", venue: "Gloucester Green",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Antiques, crafts and global street food in central Oxford.",
    url: "https://www.oxford.gov.uk", likes: 15, trust: "official" },
  { city: "Brighton", lat: 50.8225, lng: -0.1372, day: 1, time: "11:00",
    name: "Open Market Makers' Sunday", venue: "Brighton Open Market",
    category: ["market", "family"], cost: "free", vibe: "lively", indoor: "mixed",
    summary: "Independent traders, street food and live buskers.",
    url: "https://brightonopenmarket.co.uk", likes: 25, trust: "official" },
  { city: "Brighton", lat: 50.8290, lng: -0.1500, day: 8, time: "07:30",
    name: "Seafront Sunrise Yoga", venue: "Brighton Beach, Hove Lawns",
    category: ["wellbeing", "outdoors"], cost: "donation", vibe: "calm", indoor: "outdoor",
    activity_level: "low",
    summary: "Donation-based beach yoga as the sun comes up. Bring a mat.",
    url: "https://www.visitbrighton.com", likes: 22, trust: "community" },
  { city: "London", lat: 51.5074, lng: -0.1278, repeat: "weekly", dow: 0, time: "11:00",
    name: "Columbia Road Flower Market", venue: "Columbia Road, Bethnal Green",
    category: ["market", "family"], cost: "free", vibe: "lively", indoor: "outdoor",
    summary: "The famous Sunday flower market — go early, leave with a fern.",
    url: "https://columbiaroad.info", likes: 52, trust: "official" },
  { city: "London", lat: 51.5045, lng: -0.0865, day: 3, time: "10:00",
    name: "Borough Market Producers' Day", venue: "Borough Market, Southwark",
    category: ["market", "family"], cost: "free", vibe: "lively", indoor: "mixed",
    summary: "Tastings and demos from the market's independent producers.",
    url: "https://boroughmarket.org.uk", likes: 44, trust: "official" },
  { city: "London", lat: 51.5390, lng: -0.1426, day: 5, time: "14:00",
    name: "Camden Community Garden Day", venue: "Camden Garden Centre",
    category: ["charity", "outdoors", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Volunteer planting, plant swap and a cake stall for charity.",
    url: "https://www.camden.gov.uk", likes: 10, trust: "community" },
  { city: "London", lat: 51.4700, lng: -0.1100, day: 0, time: "10:00",
    name: "Brixton Makers' & Food Market", venue: "Brixton Station Road",
    category: ["market", "family"], cost: "free", vibe: "lively", indoor: "outdoor",
    summary: "Caribbean food, makers and vinyl in the heart of Brixton.",
    url: "https://www.brixtonmarket.net", likes: 30, trust: "community" },

  // ===== WEEKLY parkruns — free, every Saturday 9am =====
  { city: "Edinburgh", lat: 55.9558, lng: -3.1130, repeat: "weekly", dow: 6, time: "09:00",
    name: "Portobello parkrun", venue: "Portobello Promenade",
    category: ["sports", "outdoors"], cost: "free", vibe: "energetic", indoor: "outdoor", activity_level: "high",
    summary: "Free, friendly, timed 5k along the beach. Walk, jog or run — all welcome.",
    url: "https://www.parkrun.org.uk/portobello", likes: 28, trust: "community" },
  { city: "Glasgow", lat: 55.8270, lng: -4.3130, repeat: "weekly", dow: 6, time: "09:30",
    name: "Pollok parkrun", venue: "Pollok Country Park",
    category: ["sports", "outdoors"], cost: "free", vibe: "energetic", indoor: "outdoor", activity_level: "high",
    summary: "Free weekly 5k through the woods and parkland. Volunteers welcome too.",
    url: "https://www.parkrun.org.uk/pollok", likes: 24, trust: "community" },
  { city: "Dundee", lat: 56.4880, lng: -3.0300, repeat: "weekly", dow: 6, time: "09:30",
    name: "Camperdown parkrun", venue: "Camperdown Country Park",
    category: ["sports", "outdoors"], cost: "free", vibe: "energetic", indoor: "outdoor", activity_level: "high",
    summary: "Free weekly 5k in Dundee's biggest park. Family-friendly.",
    url: "https://www.parkrun.org.uk/camperdown", likes: 14, trust: "community" },
  { city: "Aberdeen", lat: 57.1440, lng: -2.1760, repeat: "weekly", dow: 6, time: "09:30",
    name: "Hazlehead parkrun", venue: "Hazlehead Park",
    category: ["sports", "outdoors"], cost: "free", vibe: "energetic", indoor: "outdoor", activity_level: "high",
    summary: "Free weekly 5k around Hazlehead's woods and gardens.",
    url: "https://www.parkrun.org.uk/hazlehead", likes: 12, trust: "community" },
  { city: "Inverness", lat: 57.4630, lng: -4.2410, repeat: "weekly", dow: 6, time: "09:30",
    name: "Inverness parkrun", venue: "Bught Park",
    category: ["sports", "outdoors"], cost: "free", vibe: "energetic", indoor: "outdoor", activity_level: "high",
    summary: "Free weekly 5k along the river Ness. All paces welcome.",
    url: "https://www.parkrun.org.uk/inverness", likes: 11, trust: "community" },
  { city: "Manchester", lat: 53.5350, lng: -2.2470, repeat: "weekly", dow: 6, time: "09:00",
    name: "Heaton parkrun", venue: "Heaton Park",
    category: ["sports", "outdoors"], cost: "free", vibe: "energetic", indoor: "outdoor", activity_level: "high",
    summary: "Free weekly 5k in one of Europe's biggest municipal parks.",
    url: "https://www.parkrun.org.uk/heaton", likes: 22, trust: "community" },
  { city: "Leeds", lat: 53.8090, lng: -1.5610, repeat: "weekly", dow: 6, time: "09:00",
    name: "Woodhouse Moor parkrun", venue: "Woodhouse Moor",
    category: ["sports", "outdoors"], cost: "free", vibe: "energetic", indoor: "outdoor", activity_level: "high",
    summary: "Free weekly 5k just north of the city centre.",
    url: "https://www.parkrun.org.uk/woodhousemoor", likes: 16, trust: "community" },
  { city: "Bristol", lat: 51.4490, lng: -2.6300, repeat: "weekly", dow: 6, time: "09:00",
    name: "Ashton Court parkrun", venue: "Ashton Court Estate",
    category: ["sports", "outdoors"], cost: "free", vibe: "energetic", indoor: "outdoor", activity_level: "high",
    summary: "Free weekly 5k through a deer park with city views.",
    url: "https://www.parkrun.org.uk/ashtoncourt", likes: 18, trust: "community" },
  { city: "London", lat: 51.5610, lng: -0.1630, repeat: "weekly", dow: 6, time: "09:00",
    name: "Hampstead Heath parkrun", venue: "Hampstead Heath",
    category: ["sports", "outdoors"], cost: "free", vibe: "energetic", indoor: "outdoor", activity_level: "high",
    summary: "Free, hilly weekly 5k across the Heath. Earn that coffee.",
    url: "https://www.parkrun.org.uk/hampsteadheath", likes: 26, trust: "community" },

  // ===== WEEKLY community staples =====
  { city: "Edinburgh", lat: 55.9480, lng: -3.1900, repeat: "weekly", dow: 3, time: "10:30",
    name: "Bounce & Rhyme Storytime", venue: "Central Library, George IV Bridge",
    category: ["family"], cost: "free", vibe: "creative", indoor: "indoor", activity_level: "low",
    summary: "Free songs, rhymes and stories for under-5s and their grown-ups.",
    url: "https://www.edinburghlibraries.info", likes: 9, trust: "community" },
  { city: "Glasgow", lat: 55.8625, lng: -4.2710, repeat: "weekly", dow: 2, time: "10:30",
    name: "Toddler Tales at the Mitchell", venue: "The Mitchell Library",
    category: ["family"], cost: "free", vibe: "creative", indoor: "indoor", activity_level: "low",
    summary: "Free weekly story and song session for toddlers.",
    url: "https://www.glasgowlife.org.uk/libraries", likes: 8, trust: "community" },
  { city: "Stirling", lat: 56.1180, lng: -3.9360, repeat: "weekly", dow: 0, time: "10:00",
    name: "Stirling Sunday Market", venue: "Port Street",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Weekly street market — produce, crafts and street food.",
    url: "https://www.yourstirling.com", likes: 10, trust: "community" },
  { city: "Edinburgh", lat: 55.9760, lng: -3.1700, repeat: "weekly", dow: 6, time: "10:00",
    name: "Leith Saturday Market", venue: "Dock Place, Leith",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Weekly waterside market with food stalls and local makers.",
    url: "https://www.leithmarket.com", likes: 17, trust: "community" },

  // ===== EVERGREEN places — free & worth a visit any day =====
  { city: "Edinburgh", lat: 55.9468, lng: -3.1903, evergreen: true, time: "10:00",
    name: "National Museum of Scotland", venue: "Chambers Street",
    category: ["family", "wellbeing"], cost: "free", vibe: "creative", indoor: "indoor",
    summary: "Free entry, open daily — dinosaurs, Dolly the sheep and a rooftop view.",
    url: "https://www.nms.ac.uk/national-museum-of-scotland", likes: 40, trust: "official" },
  { city: "Edinburgh", lat: 55.9510, lng: -3.1956, evergreen: true, time: "10:00",
    name: "Scottish National Gallery", venue: "The Mound",
    category: ["wellbeing", "family"], cost: "free", vibe: "calm", indoor: "indoor",
    summary: "Free entry — Scotland's great art collection in the heart of the city.",
    url: "https://www.nationalgalleries.org", likes: 19, trust: "official" },
  { city: "Edinburgh", lat: 55.9650, lng: -3.2100, evergreen: true, time: "10:00",
    name: "Royal Botanic Garden", venue: "Arboretum Place",
    category: ["outdoors", "wellbeing", "family"], cost: "free", vibe: "calm", indoor: "outdoor",
    summary: "70 acres of free gardens and glasshouses. Lovely any day off.",
    url: "https://www.rbge.org.uk", likes: 23, trust: "official" },
  { city: "Edinburgh", lat: 55.9550, lng: -3.1820, evergreen: true, time: "",
    name: "Calton Hill", venue: "Calton Hill",
    category: ["outdoors"], cost: "free", vibe: "relaxed", indoor: "outdoor", activity_level: "medium",
    summary: "The best easy view in Edinburgh — monuments, sunset and the skyline.",
    url: "https://www.edinburgh.org", likes: 21, trust: "official" },
  { city: "Glasgow", lat: 55.8686, lng: -4.2906, evergreen: true, time: "10:00",
    name: "Kelvingrove Art Gallery & Museum", venue: "Argyle Street",
    category: ["family", "wellbeing"], cost: "free", vibe: "creative", indoor: "indoor",
    summary: "Free entry, open daily — Glasgow's beloved museum with daily organ recitals.",
    url: "https://www.glasgowlife.org.uk/museums/venues/kelvingrove-art-gallery-and-museum", likes: 35, trust: "official" },
  { city: "Glasgow", lat: 55.8656, lng: -4.3057, evergreen: true, time: "10:00",
    name: "Riverside Museum", venue: "100 Pointhouse Place",
    category: ["family"], cost: "free", vibe: "creative", indoor: "indoor",
    summary: "Free transport museum on the Clyde, plus the Tall Ship outside.",
    url: "https://www.glasgowlife.org.uk/museums/venues/riverside-museum", likes: 20, trust: "official" },
  { city: "Glasgow", lat: 55.8270, lng: -4.3170, evergreen: true, time: "",
    name: "Pollok Country Park", venue: "2060 Pollokshaws Road",
    category: ["outdoors", "family"], cost: "free", vibe: "calm", indoor: "outdoor", activity_level: "medium",
    summary: "Highland cows, woodland trails and the Burrell Collection. Free.",
    url: "https://www.glasgow.gov.uk", likes: 15, trust: "official" },
  { city: "Falkirk", lat: 56.0194, lng: -3.7556, evergreen: true, time: "",
    name: "The Kelpies & Helix Park", venue: "The Helix",
    category: ["outdoors", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "The 30m horse-head sculptures and a big free family park. Open all hours.",
    url: "https://www.thehelix.co.uk", likes: 25, trust: "official" },
  { city: "London", lat: 51.5194, lng: -0.1270, evergreen: true, time: "10:00",
    name: "The British Museum", venue: "Great Russell Street",
    category: ["family", "wellbeing"], cost: "free", vibe: "creative", indoor: "indoor",
    summary: "Free entry — the Rosetta Stone, mummies and two million years of history.",
    url: "https://www.britishmuseum.org", likes: 47, trust: "official" },
  { city: "London", lat: 51.5076, lng: -0.0994, evergreen: true, time: "10:00",
    name: "Tate Modern", venue: "Bankside",
    category: ["wellbeing", "family"], cost: "free", vibe: "creative", indoor: "indoor",
    summary: "Free modern art in a former power station, with river views up top.",
    url: "https://www.tate.org.uk/visit/tate-modern", likes: 34, trust: "official" },
  { city: "London", lat: 51.4967, lng: -0.1764, evergreen: true, time: "10:00",
    name: "Natural History Museum", venue: "Cromwell Road",
    category: ["family"], cost: "free", vibe: "creative", indoor: "indoor",
    summary: "Free entry — the blue whale, dinosaurs and a wildlife garden.",
    url: "https://www.nhm.ac.uk", likes: 45, trust: "official" },
  { city: "Manchester", lat: 53.4775, lng: -2.2520, evergreen: true, time: "10:00",
    name: "People's History Museum", venue: "Left Bank, Spinningfields",
    category: ["family", "wellbeing"], cost: "free", vibe: "creative", indoor: "indoor",
    summary: "Free museum of democracy, protest and everyday working life.",
    url: "https://phm.org.uk", likes: 13, trust: "official" },

  // ===== more one-offs for spread =====
  { city: "Edinburgh", lat: 55.9521, lng: -3.1889, day: 7, time: "12:00",
    name: "Grassmarket Summer Fair", venue: "Grassmarket",
    category: ["market", "family"], cost: "free", vibe: "lively", indoor: "outdoor",
    summary: "Crafts, food and live music under the castle for one day.",
    url: "https://www.greatergrassmarket.co.uk", likes: 18, trust: "community" },
  { city: "Glasgow", lat: 55.8580, lng: -4.2900, day: 9, time: "13:00",
    name: "Merchant City Street Food Sunday", venue: "Candleriggs",
    category: ["market", "family"], cost: "free", vibe: "lively", indoor: "outdoor",
    summary: "Independent kitchens and live sets in the Merchant City.",
    url: "https://www.merchantcityglasgow.com", likes: 21, trust: "community" },
  { city: "Dundee", lat: 56.4620, lng: -2.9700, day: 13, time: "10:00",
    name: "Broughty Ferry Beach Day", venue: "Broughty Ferry Beach",
    category: ["outdoors", "family"], cost: "free", vibe: "relaxed", indoor: "outdoor",
    summary: "Sandcastles, rockpools and the castle by the sea.",
    url: "https://www.dundee.com", likes: 12, trust: "community" },
  { city: "Newcastle", lat: 54.9700, lng: -1.6100, day: 11, time: "11:00",
    name: "Ouseburn Makers' Market", venue: "Ouseburn Valley",
    category: ["market", "family"], cost: "free", vibe: "lively", indoor: "mixed",
    summary: "Makers, street food and city farm in Newcastle's creative valley.",
    url: "https://www.ouseburn.co.uk", likes: 14, trust: "community" },
  { city: "Liverpool", lat: 53.4010, lng: -2.9660, day: 15, time: "11:00",
    name: "Lark Lane Vintage Market", venue: "Lark Lane",
    category: ["market", "family"], cost: "free", vibe: "relaxed", indoor: "mixed",
    summary: "Vintage, records and brunch near Sefton Park.",
    url: "https://www.visitliverpool.com", likes: 13, trust: "community" },
];

const W3W = ["spice.ramp.state", "stows.ages.take", "cafe.robot.daring", "led.gone.needs",
  "trip.tides.salt", "rock.faced.bands", "soft.melt.dined", "vase.curve.lined",
  "moss.lake.fern", "gull.tide.warm", "kiln.brick.song", "pier.salt.fair"];

// Each RAW entry expands into one or more dated instances:
//  - { day }              one-off on a fixed offset from today
//  - { repeat:'weekly', dow }  every week on that weekday, across the window
//  - { evergreen:true }   always-on place: one entry spanning the whole window
function occurrences(e) {
  if (e.evergreen) return [{ off: 0, span: WINDOW_DAYS, sfx: "ever" }];
  if (e.repeat === "weekly") {
    const out = [];
    for (let k = 0, first = nextDow(e.dow); first + k * 7 <= WINDOW_DAYS; k += 1) {
      out.push({ off: first + k * 7, span: 0, sfx: `w${k}` });
    }
    return out;
  }
  return [{ off: e.day || 0, span: 0, sfx: "d" }];
}

export function buildCuratedEvents() {
  const events = [];
  RAW.forEach((e, i) => {
    const community = e.trust === "community";
    const citySlug = e.city.toLowerCase().replace(/\s+/g, "");
    occurrences(e).forEach((o) => {
      const start = addDaysYmd(o.off);
      events.push({
        id: `showcase_${i}_${citySlug}_${o.sfx}`,
        name: e.name,
        start_date: start,
        end_date: o.span ? addDaysYmd(o.off + o.span) : start,
        time: e.time,
        category: e.category,
        cost: e.cost,
        venue: e.venue,
        city: e.city,
        url: e.url,
        source_event_url: e.url,
        source_feed_url: "",
        what3words: W3W[i % W3W.length],
        lat: near(e.lat, i + 1),
        lng: near(e.lng, i + 7),
        summary: e.summary,
        vibe: e.vibe,
        indoor: e.indoor,
        activity_level: e.activity_level || "low",
        audience: ["all-ages"],
        accessibility: ["step-free"],
        source: "showcase",
        source_trust: community ? "community" : "official",
        verification_status: community ? "community-submitted" : "feed-listing",
        likes: e.likes,
        popularity: e.likes,
        last_seen_at: new Date().toISOString(),
      });
    });
  });
  return events;
}

export default buildCuratedEvents;
